spring:
  application:
    name: place-service

  datasource:
    url: jdbc:mysql://mysql:3306/travel
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  data:
    redis:
      host: redis
      port: 6379

  cache:
    type: redis

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: place-service

server:
  port: 8080

logging:
  level:
    root: INFO